name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'frontend/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Frontend
        run: npm install && npm run build
        working-directory: ./frontend

      - name: Deploy to Firebase Hosting (Prod)
        if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GOTHIC_SLED_375305 }}'
          channelId: live
          projectId: gothic-sled-375305
          entryPoint: frontend/

      - name: Deploy to Firebase Hosting (Staging)
        if: github.ref == 'refs/heads/staging'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAGING }}'
          channelId: staging
          projectId: whatcomcoders-prod
          entryPoint: frontend/
