name: Deploy Backend to Google App Engine

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup gcloud CLI
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Configure gcloud CLI
      - name: Set up Cloud SDK
        run: |
          gcloud config set project gothic-sled-375305
          gcloud config set app/cloud_build_timeout 1000

      # Deploy to Google App Engine (only for merges, not for PRs)
      - name: Deploy to App Engine
        if: github.event_name == 'push'
        run: gcloud app deploy backend/app.yaml --project gothic-sled-375305
