name: Deploy Backend to Google App Engine

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup gcloud CLI
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Configure gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: gothic-sled-375305
          # service_account_key: ${{ secrets.GCP_SA_KEY }}

        # run: |
        #   gcloud config set project gothic-sled-375305
        #   gcloud config set app/cloud_build_timeout 1000

      # Deploy to Google App Engine (only for merges, not for PRs)
      - name: Deploy to App Engine
        if: github.event_name == 'push'
        run: |
          if [[ $GITHUB_REF == 'refs/heads/staging' ]]; then
            gcloud app deploy --project=whatcomcoders-staging --version=$(echo $GITHUB_REF | sed 's/refs\/heads\///') --promote
          else
            gcloud app deploy backend/app.yaml --project gothic-sled-375305 --version=$(echo $GITHUB_REF | sed 's/refs\/heads\///') --no-promote
          fi
